GET https://webprogra-api-anhyamamfkdebbcg.eastus2-01.azurewebsites.net/usuario

####

GET http://localhost:4001/curso/4

####

POST https://webprogra-api-anhyamamfkdebbcg.eastus2-01.azurewebsites.net/usuario
Content-Type: application/json

{
       "id": 1,
        "nombre": "sandra",
        "apellido": "pedro",
        "email": "renzo@gmail.com",
        "password": "123456",
        "rol": "admin"
       
       


       
}

###

PUT http://localhost:4001/producto
Content-Type: application/json

{
        "id": 1,
        "nombre": "minecraft"
        
}

####

DELETE http://localhost:4001/carrera/1