GET https://webprogra-api-anhyamamfkdebbcg.eastus2-01.azurewebsites.net/producto

####

GET http://localhost:4001/curso/4

####

POST https://webprogra-api-anhyamamfkdebbcg.eastus2-01.azurewebsites.net/usuario/login
Content-Type: application/json

{
        "email": "laura@gmail.com",
        "password":"contr303"
  
}

###

PUT https://webprogra-api-anhyamamfkdebbcg.eastus2-01.azurewebsites.net/p
Content-Type: application/json

{
        "id": 28,
        "nombre": "minecraft"
        
}

####

DELETE https://webprogra-api-anhyamamfkdebbcg.eastus2-01.azurewebsites.net/producto/28